name 'CookbookJavascriptKata'
maintainer 'Stacey Vetzal'
maintainer_email 'stacey@mojility.ca'
license 'MIT'
description 'Set up a basic NodeJS runtime environment for Javascript Coaching kata'
long_description 'Set up a basic NodeJS runtime environment for Javascript Coaching kata'
version '0.9.0'
